packages:
  - 'packages/*'
  - 'playground'
  - 'runtime/*'
  - 'vue-components/*'
  - 'react-components/*'
  - 'eslint-config'

catalog:
  vue: ^3.5.24
  '@vue/compiler-sfc': ^3.5.24
  vite: ^7.2.4
  typescript: "^5.9.3"
  