packages:
  - "packages/*"
  - "playground"
  - "runtime/*"
  - "vue-components/*"
  - "react-components/*"
  - "eslint-config"

catalog:
  "@vue/compiler-sfc": ^3.5.40
  typescript: "^6.0.3"
  vite: ^8.1.5
  vue: ^3.5.40

overrides:
  element-plus: ^2.14.3
  vue: ^3.5.40